<?php

namespace  whiteSuit\review\models;

use yii\helpers\ArrayHelper;
use common\models\Advert;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "advert_reviews".
 *
 * @property int $id
 * @property int $review_id
 * @property int $advert_id
 * @property int $sort
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Advert $advert
 * @property Reviews $review
 */

class AdvertReviews extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'advert_reviews';
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(),[
            'date_filter' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],

        ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['review_id', 'advert_id'], 'required'],
            [['review_id', 'advert_id', 'sort', 'created_at', 'updated_at'], 'integer'],
            [['advert_id'], 'exist', 'skipOnError' => true, 'targetClass' => Advert::className(), 'targetAttribute' => ['advert_id' => 'id']],
            [['review_id'], 'exist', 'skipOnError' => true, 'targetClass' => Reviews::className(), 'targetAttribute' => ['review_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'review_id' => Yii::t('app', 'Review ID'),
            'advert_id' => Yii::t('app', 'Advert ID'),
            'sort' => Yii::t('app', 'Sort'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdvert()
    {
        return $this->hasOne(Advert::className(), ['id' => 'advert_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReview()
    {
        return $this->hasOne(Reviews::className(), ['id' => 'review_id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\modules\review\queries\AdvertReviewsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\modules\review\queries\AdvertReviewsQuery(get_called_class());
    }
}
