<?php


namespace common\modules\review\widgets;


use common\components\DdHelper;
use common\models\Advert;
use common\models\Product;
use common\modules\review\forms\ReviewForm;
use common\modules\review\models\Reviews;
use yii\base\Exception;
use yii\base\Widget;
use yii\db\ActiveRecord;
use yii\helpers\Url;

class ReviewWidget extends Widget
{
    /**
     * @var Product | Advert | ActiveRecord
     */
    public $model;

    protected $_action;

    public $type = Reviews::TYPE_PRODUCT;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!$this->model){
            throw new Exception(\Yii::t('app','Model required'));
        }
    }

    public function run()
    {
        $form = new ReviewForm();
        $form->model_id = $this->model->id;
        $form->type = $this->type;
        return $this->render('review',[
            'model'=>$this->model,
            'reviewForm'=>$form,
            'action'=>$this->action,
            'reviews'=> $this->getReviews()
        ]);
    }

    public function setAction($value)
    {
        $this->_action = $value;
    }
    public function getAction()
    {
        if(!$this->_action){
            $this->_action = Url::to(['/review/review/add']);
        }
        return $this->_action;
    }

    protected function getReviews()
    {
        $query = Reviews::find()->joinUser();
        if($this->type == Reviews::TYPE_PRODUCT){
            $query->joinProducts()->productId($this->model->id);
        }
        if($this->type == Reviews::TYPE_ADVERT) {
            $query->joinAdverts()->advertId($this->model->id);
        }

        return $query->active()->all();
    }



}